language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
# This only works with docker images provided
# To run:
#   docker-compose up -d
#   docker-composer run -rm php vendor/bin/behat -f progress
#
#  - vendor/bin/behat -f progress

after_script:
- if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi